/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bb87da40-f5c7-4187-a3d9-c99efb1363d8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xklx12JCF",
    "aws_user_pools_web_client_id": "6pqmp5n7o8aovd1ka4lktblfbi",
    "oauth": {},
    "aws_mobile_analytics_app_id": "421fc4e0f2894e1fae945349fd72dbd2",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "edelmandevapi",
            "endpoint": "https://fz8opgi7b5.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://xskq2pbv25f5pe3fa7cxx47gue.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ullumz67vjaital2rokmrmaixu",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "edelmandevdynostore-dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
